# Train a Random Forest Classifier to predict next-day rain in Australia

## Executive Summary

Australians are known for loving the outdoors. However, while sunny weather is common in Australia, there are also many rainy days. To plan for outdoor activities, work or travel that depends on the weather, being able to predict whether it will rain tomorrow is vital. 

In this notebook, we will train and evaluate a Random Forest Classifier to predict whether it will rain tomorrow based on today's weather readings. 

Based on earlier EDA and experiments (which are included in the notebook named 1_EDA_InitialModelvF), below are a quick recap on the approach for this notebook. 

**[Completed] Step 1. Set up Jupyter Lab on GCP AI Platform**

**Step 2. Perform data preprocessing** 
1. Convert Date column from string to datetime & create Year & Month features
2. Handle missing values for numerical features: forward fill method
3. Remove records with missing labels (i.e. RainTomorrow is null)
4. Split data into a training set and a test set: remove Date feature due to high cardinality
5. Handle missing values and encoding categorical features with one-hot encoding and binary encoding
6. Feature scaling: standard scaler for simplicity
7. Correct imbalanced dataset with SMOTE (Synthetic Minority Oversampling Technique)

**Step 3. Fine-tune Random Forest Classifier using RandomizedSearchCV and GridSearchCV**

**Step 4. Evaluate the Random Forest model with test data**

**Step 5. Save the best Random Forest model**

Note: Based on earlier experiment with GCP AI Platform, RandomizedSearchCV might take too long to fit if I use the full dataset. To speed up the process, I would perform fine-tuning with 25% of the randomly sampled records.

## 1. Load required Python libraries and data

For this project, I am using the 10 years of daily weather observations from many location across Australia obtained from [Kaggle](https://www.kaggle.com/jsphyg/weather-dataset-rattle-package). The dataset has been saved into Google Cloud Storage to allow ease of access and mimic a central data depository (e.g. data lake) for a business.

In [2]:
from google.cloud import storage
import os
import pandas as pd
import numpy as np
from numpy import asarray
from datetime import datetime
from random import randint

# Ignore all warnings
import warnings
warnings.filterwarnings("ignore")

# Data preparation
from sklearn.model_selection import train_test_split
import category_encoders as ce
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# ML model training
import sklearn
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import AdaBoostClassifier

# Model evaluation & selection
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

# Fine-tune model performance
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

# Save ML model
import pickle

In [2]:
# Display all columns without truncation in dataframes
pd.set_option('display.max_columns', 500)

In [3]:
# Load weather observation data
weatherAUS_path = "gs://australiarain-aiplatform/input/weatherAUS.csv"
weather_df = pd.read_csv(weatherAUS_path)
weather_df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

## 2. Data Preprocessing

### 2.1. Date

In [4]:
# Convert Date column to the correct data type
weather_df['Date'] = pd.to_datetime(weather_df['Date'])

# Extract Month & Year from Date column
weather_df['Month'] = pd.DatetimeIndex(weather_df['Date']).month
weather_df['Year'] = pd.DatetimeIndex(weather_df['Date']).year

## 2.2. Handle missing values for numerical features

Weather observations greatly vary according to specific locations and seasons. Therefore, it would be flawed to impute missing numerical values with the mean value of the entire population. I decided to impute missing values for all numerical features with forward fill method since it would best reflect the locations and seasonality based on how the data is currently sorted.

In [5]:
# Forward fill missing values
weather_df[['MinTemp', 'MaxTemp', 'Temp9am', 'Temp3pm', 'Rainfall', 
            'Evaporation', 'Sunshine', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 
           'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm']] = weather_df[['MinTemp', 'MaxTemp', 'Temp9am', 'Temp3pm', 'Rainfall', 'Evaporation', 'Sunshine', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 
           'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm']].fillna(method='ffill')
weather_df.isnull().sum()

Date                 0
Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation       6049
Sunshine          6049
WindGustDir      10326
WindGustSpeed        0
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             2
Temp9am              0
Temp3pm              0
RainToday         3261
RainTomorrow      3267
Month                0
Year                 0
dtype: int64

There are 2 records with missing Cloud3pm. I will remove these 2 records since the 2 records are insignificant to the overall information. 

However, Evaporation and Sunshine have a lot more missing values missing after applying forward fill method. Assuming weather observations would be similar for nearly locations, I will impute the remaining missing values for numerical features with observations at neighbouring places. Specifically, Albury's incomplete observations will be impute with Canberra's readings. Badgerys Creek's null values will be replaced with Sydney's observations.

In [6]:
# Remove 2 records having null Cloud3pm
weather_df = weather_df[weather_df['Cloud3pm'].notnull()]

In [7]:
# Extract observations at Canberra
canberra_observations = weather_df.query('Location == "Canberra"')[['Date','Evaporation', 'Sunshine']]

# Extract Albury's records
albury_observations = weather_df.query('Location == "Albury"')

# Merge 2 dataframes and impute missing values
albury_merge = pd.merge(albury_observations, canberra_observations, on = ['Date', 'Date'])
albury_merge['Evaporation'] = albury_merge['Evaporation_y']
albury_merge['Sunshine'] = albury_merge['Sunshine_y']
albury_merge = albury_merge.drop(columns = ['Evaporation_x', 'Sunshine_x', 'Evaporation_y', 'Sunshine_y'])
albury_merge

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Month,Year,Evaporation,Sunshine
0,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,...,8.0,2.0,21.0,23.2,No,No,12,2008,10.2,13.2
1,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,...,8.0,2.0,18.1,26.5,No,No,12,2008,11.0,10.8
2,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,...,7.0,8.0,17.8,29.7,No,No,12,2008,6.6,8.1
3,2008-12-06,Albury,14.6,29.7,0.2,WNW,56.0,W,W,19.0,...,7.0,8.0,20.6,28.9,No,No,12,2008,6.4,9.4
4,2008-12-07,Albury,14.3,25.0,0.0,W,50.0,SW,W,20.0,...,1.0,8.0,18.1,24.6,No,No,12,2008,12.4,12.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,2017-06-21,Albury,1.2,15.2,0.4,ENE,15.0,NaN,NNE,0.0,...,8.0,7.0,2.9,14.3,No,No,6,2017,1.6,2.8
3034,2017-06-22,Albury,0.8,13.4,0.0,W,17.0,S,NaN,6.0,...,8.0,1.0,3.6,13.3,No,No,6,2017,1.6,2.8
3035,2017-06-23,Albury,1.1,11.9,0.0,SE,44.0,SSE,SSE,9.0,...,8.0,1.0,2.7,10.2,No,No,6,2017,1.6,2.8
3036,2017-06-24,Albury,1.1,14.1,0.2,WSW,28.0,SW,W,4.0,...,7.0,6.0,3.9,13.1,No,No,6,2017,1.6,2.8
3037,2017-06-25,Albury,3.9,10.9,0.0,NNW,28.0,S,NaN,6.0,...,7.0,8.0,6.4,8.8,No,Yes,6,2017,1.6,2.8

In [8]:
# Extract observations at Sydney
sydney_observations = weather_df.query('Location == "Sydney"')[['Date','Evaporation', 'Sunshine']]

# Extract Albury's records
badgery_observations = weather_df.query('Location == "BadgerysCreek"')
badgery_observations

# Merge 2 dataframes and impute missing values
badgery_merge = pd.merge(badgery_observations, sydney_observations, on = ['Date', 'Date'])
badgery_merge['Evaporation'] = badgery_merge['Evaporation_y']
badgery_merge['Sunshine'] = badgery_merge['Sunshine_y']
badgery_merge = badgery_merge.drop(columns = ['Evaporation_x', 'Sunshine_x', 'Evaporation_y', 'Sunshine_y'])
badgery_merge

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Month,Year,Evaporation,Sunshine
0,2009-01-01,BadgerysCreek,13.3,34.2,0.0,W,61.0,NNE,NaN,11.0,...,7.0,8.0,21.0,8.8,No,No,1,2009,9.8,12.9
1,2009-01-02,BadgerysCreek,14.7,26.1,0.0,SE,46.0,SE,SE,7.0,...,7.0,8.0,20.7,22.2,No,No,1,2009,11.0,5.9
2,2009-01-03,BadgerysCreek,13.6,22.3,0.0,NNE,30.0,ESE,NE,6.0,...,7.0,8.0,17.9,21.7,No,No,1,2009,9.0,0.5
3,2009-01-04,BadgerysCreek,17.7,31.2,0.0,NE,39.0,NNE,N,9.0,...,7.0,8.0,22.0,30.6,No,No,1,2009,5.4,11.3
4,2009-01-05,BadgerysCreek,15.5,38.8,0.0,SW,50.0,NNE,W,7.0,...,7.0,8.0,22.7,37.6,No,No,1,2009,10.0,12.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3004,2017-06-21,BadgerysCreek,4.1,19.0,0.2,SSE,26.0,SW,SE,6.0,...,7.0,8.0,8.5,16.4,No,No,6,2017,2.0,7.8
3005,2017-06-22,BadgerysCreek,6.8,18.3,0.0,SW,17.0,SW,NNW,11.0,...,7.0,8.0,10.7,17.9,No,No,6,2017,2.0,9.2
3006,2017-06-23,BadgerysCreek,3.8,16.8,0.2,SW,17.0,NaN,N,0.0,...,7.0,8.0,6.8,16.0,No,No,6,2017,2.4,2.7
3007,2017-06-24,BadgerysCreek,2.7,18.8,0.0,SSW,24.0,NW,WSW,4.0,...,7.0,8.0,8.6,18.5,No,No,6,2017,1.4,9.3
3008,2017-06-25,BadgerysCreek,0.8,18.6,0.2,WSW,31.0,NaN,WSW,0.0,...,7.0,8.0,6.9,17.8,No,No,6,2017,3.4,9.4

In [9]:
# Delete all Albury and Badgerys Creek's records (currently having missing values)
weather_df = weather_df[weather_df['Sunshine'].notnull()]
weather_df.shape

# Append Albury and Badgerys Creek's records (with missing values imputed)
weather_df = weather_df.append(albury_merge, ignore_index = True, verify_integrity = True)
weather_df = weather_df.append(badgery_merge, ignore_index = True, verify_integrity = True)

weather_df.shape

(145458, 25)

### 2.3. Handle missing labels

In [10]:
# Remove all records without labels (i.e. RainTomorrow is null)
weather_df = weather_df[weather_df['RainTomorrow'].notnull()]

### 2.4. Choose 25% of the dataset for model training (to speed up the process)

In [11]:
# Random sampling 25% of the dataset to speed up the model training process
weather_df_condensed = weather_df.sample(frac = .5)
weather_df_condensed

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Month,Year
34293,2011-03-16,Williamtown,15.4,28.1,0.0,4.2,7.3,NaN,31.0,NW,...,1017.7,1015.9,4.0,5.0,21.4,25.1,No,No,3,2011
19835,2013-12-21,Penrith,23.7,32.2,0.0,4.0,8.0,S,31.0,SSE,...,1015.1,1014.2,7.0,2.0,25.2,30.4,No,No,12,2013
118615,2011-05-22,SalmonGums,9.7,17.0,0.4,1.6,7.9,SW,37.0,SW,...,1028.6,1026.0,1.0,3.0,12.9,16.0,No,Yes,5,2011
54080,2014-08-08,Bendigo,7.3,13.5,0.0,2.2,2.8,NW,24.0,NaN,...,1032.1,1029.9,8.0,8.0,9.7,12.8,No,No,8,2014
69489,2010-07-13,Portland,7.1,15.2,0.0,2.4,5.0,W,57.0,N,...,1005.0,997.1,5.0,6.0,10.4,12.9,No,Yes,7,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29670,2015-04-08,SydneyAirport,14.6,23.0,0.4,5.6,4.6,WSW,65.0,WSW,...,1010.8,1013.2,3.0,6.0,18.4,20.6,No,No,4,2015
90379,2008-10-17,Adelaide,12.8,31.0,0.0,5.2,12.0,N,30.0,N,...,1020.3,1017.3,8.0,8.0,22.0,30.5,No,No,10,2008
118900,2012-03-02,SalmonGums,3.6,24.7,0.0,1.6,7.9,ESE,39.0,E,...,1028.6,1026.0,1.0,3.0,17.7,23.3,No,No,3,2012
138519,2015-01-16,Uluru,19.9,39.3,0.0,10.0,10.7,E,48.0,ENE,...,1010.4,1007.0,1.0,1.0,29.7,37.4,No,No,1,2015
55532,2010-02-04,Sale,21.1,30.4,0.0,10.6,3.2,E,59.0,ENE,...,1010.5,1007.6,6.0,8.0,24.9,25.9,No,Yes,2,2010

### 2.5. Split dataset into a training set and a test set

In [12]:
# Separate label (y) and predicting features (X)
X = weather_df_condensed.drop(columns = ['RainTomorrow', 'Date'])
y = weather_df_condensed['RainTomorrow']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### 2.6. Handle missing values and encoding for categorical values

As mentioned earlier, missing values for categorical features appear systematically. Therefore, I will treat missing values as another value and encode it accordingly. 

Machine learning and deep learning models, like those in Keras, require all input and output variables to be numeric. This means that if our data contains categorical data, we must encode it to numbers before we can fit and evaluate a model. 

I chose one-hot encoding since all categorical features neither have high cardinality (to consider binary encoding) nor imply order (to consider ordinal encoding).

In [13]:
# One-hot encoding with category_encoders library

encoder = ce.OneHotEncoder(cols = ['RainToday'], return_df = True)
X_train_transformed = encoder.fit_transform(X_train, y_train)
X_test_transformed = encoder.transform(X_test)
X_train_transformed

# Binary encoding with category_encoders library
encoder = ce.BinaryEncoder(cols = ['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm'], return_df = True)
X_train_transformed = encoder.fit_transform(X_train_transformed, y_train)
X_test_transformed = encoder.transform(X_test_transformed)
X_train_transformed

,Location_0,Location_1,Location_2,Location_3,Location_4,Location_5,Location_6,MinTemp,MaxTemp,Rainfall,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday_1,RainToday_2,RainToday_3,Month,Year
58373,0,0,0,0,0,0,1,9.8,17.4,3.0,...,1010.4,7.0,4.0,10.1,16.8,1,0,0,8,2009
21294,0,0,0,0,0,1,0,4.2,18.2,0.0,...,1008.7,7.0,2.0,8.7,18.0,0,1,0,6,2009
44442,0,0,0,0,0,1,1,10.6,27.4,0.0,...,1018.9,8.0,8.0,16.6,26.6,0,1,0,3,2013
41545,0,0,0,0,1,0,0,-2.9,14.7,0.0,...,1026.4,3.0,4.0,2.3,13.3,0,1,0,7,2013
140398,0,0,0,0,1,0,1,4.4,20.8,0.0,...,1013.9,8.0,3.0,9.8,19.3,0,1,0,9,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117531,0,1,0,1,1,1,0,10.8,21.6,0.0,...,1019.7,1.0,2.0,16.1,19.5,0,1,0,10,2016
2403,0,1,0,1,0,0,0,17.6,31.8,0.0,...,1015.4,1.0,4.0,20.8,30.7,0,1,0,10,2015
115455,0,1,0,1,1,1,0,13.9,28.1,0.0,...,1015.4,4.0,7.0,20.8,26.3,0,1,0,11,2010
48675,0,1,0,0,1,0,1,-1.0,6.0,0.0,...,1016.0,8.0,8.0,1.0,5.2,0,1,0,6,2016
68486,0,0,1,1,1,1,1,4.5,20.2,0.0,...,1023.3,0.0,4.0,11.1,18.8,0,1,0,4,2016

### 2.7. Feature Scaling

In [14]:
scaler = StandardScaler()
X_train_transformed = scaler.fit_transform(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test_transformed)
X_train_transformed

array([[ 0.        , -0.76407094, -0.72368693, ..., -0.10159051,
         0.46749309, -1.4800825 ],
       [ 0.        , -0.76407094, -0.72368693, ..., -0.10159051,
        -0.11503993, -1.4800825 ],
       [ 0.        , -0.76407094, -0.72368693, ..., -0.10159051,
        -0.98883945,  0.0945894 ],
       ...,
       [ 0.        ,  1.30877899, -0.72368693, ..., -0.10159051,
         1.34129262, -1.08641453],
       [ 0.        ,  1.30877899, -0.72368693, ..., -0.10159051,
        -0.11503993,  1.27559332],
       [ 0.        , -0.76407094,  1.38181299, ..., -0.10159051,
        -0.69757294,  1.27559332]])

### 2.8. Correct imbalanced dataset by oversampling with SMOTE

It is observed that the number of days with RainTomorrow = Yes is much lower than that of RainTomorrow = No. Such an imbalanced dataset could potentially explain the poor prediction performance for RainTomorrow = Yes indicated in the confusion matrix across all ML models. 

One approach to address imbalanced datasets is to oversample the minority class. There are 2 methods to oversample the minority class. 
1. Duplicate examples in the minority class: simple to implement but does not add any new information to the model 
2. Synthesis new examples from the existing samples with Synthetic Minority Oversampling Technique (SMOTE)

I decided to go with SMOTE because it adds new information to the model, which hopefully translates to better performance. To avoid data leakage (when information that would not be available at prediction time is used when building the model), I will only be resample the training dataset instead of the entire dataset.

In [15]:
X_resampled, y_resampled = SMOTE().fit_resample(X_train_transformed, y_train)

## 3. Fine-tune Random Forest Classifier

Since Random Forest results in the best performing model so far, I will use randomizedsearch and gridsearch to further fine-tune my hyperparameters for the Random Forest model. The code and the approach is adopted from [this article](https://towardsdatascience.com/hyperparameter-tuning-the-random-forest-in-python-using-scikit-learn-28d2aa77dd74) written by Will Koehrsen. [Another article](https://www.analyticsvidhya.com/blog/2020/03/beginners-guide-random-forest-hyperparameter-tuning/) has also greatly influenced how I specify the range for parameters to be assessed. 

**Overall approach for fine-tuning**

According to the article, since I do not have a concrete idea of the best hyperparameters for Random Forest Classifier, the first step will be to evaluate a wide range of values for each hyperparameter with RandomizedSearchCV. By doing that, I can obtain a rough idea of ideal hyperparameters ranges based on the best parameters found through the random search. 

Given the ideal ranges to concentrate our search, the next step would be to explicitly specify every combination of hyperparameters to try with GridSearchCV. Instead of randomly sampling from a set of hyperparameter combinations (like RandomizedSearchCV), GridSearchCV would evaluate all combinations we define, thus providing an accurate combination of hyperparameters with the best performance. 

**Diminising return and when to stop fine-tuning**

Before fine-tuning, it is noted that accuracy, precision and recall of the existing Random Forest model are 0.90 or beyond. Such performance is acceptable for a general rain forecast solution. 

Although I can continue trying different combinations of hyperparameters to improve the model performance, there will come a point that I would reach diminishing returns for hyperparameter tuning. In other words, performance improvement will not worth the time and effort spent on fine-tuning. Therefore, if after the first round of RandomizedSearchCV and GridSearchCV, the model performance does not improve beyond 2%, I will stop fine-tuning.

### 3.1. Initial state of Random Forest Classifier

To monitor the performance improvement owing to fine-tuning, I will first establish a benchmark by calculating various metrics for the default Random Forest Classifier.

In [ ]:
# Calculate F1 score for the base model 
start_time = datetime.now()
forest_clf = RandomForestClassifier(random_state = 42)
forest_clf.fit(X_resampled, y_resampled)
y_train_pred = cross_val_predict(forest_clf, X_resampled, y_resampled, cv = 10)
end_time = datetime.now()
print('Total running time:', (end_time - start_time).total_seconds())

base_model_f1_score = f1_score(y_resampled, y_train_pred, pos_label = 'Yes')

In [ ]:
base_model_f1_score

### 3.2. Narrow the search with RandomizedSearchCV

Although there are many hyperparameters that could be fine-tuned, based on [scikit-learn documentation](https://scikit-learn.org/stable/modules/ensemble.html#random-forest-parameters), I will focus on fine-tuning the following 6 parameters. 

**1. n_estimators: the number of trees in the forest**
- The larger the better, but also the longer it will take to compute.
- Results will stop getting significantly better beyond a critical number of trees

**2. max_features: the size of the randome subsets of features to consider when splitting a node**
- The lower the greater the reduction of variance, but also the greater the increase in bias
- Empirical good default values are max_features=None and max_features="sqrt" (i.e. use a random subset of size sqrt(n_features) 

**3. max_depth: the maximum number of levels in each decision tree**

**4. min_samples_split: the minimum number of data points placed in the node before the node is split**

**5. min_samples_leaf: the maximum number of data points allowed in a leaf node**

**6. bootstrap: method for sampling data points**